# Cloud Build configuration (cloudbuild.yaml)
steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/webapp:$BUILD_ID', '.']
  
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/webapp:$BUILD_ID']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'webapp-service'
      - '--image=gcr.io/$PROJECT_ID/webapp:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'

# Cloud Deploy pipeline configuration
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: webapp-pipeline
spec:
  stages:
  - targetId: staging
    profiles: [staging]
  - targetId: production
    profiles: [production]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
spec:
  run:
    location: projects/PROJECT_ID/locations/us-central1
    
